# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.


title: Feng Shao 邵锋
description: Bay is a minimal Jekyll Theme.
baseurl: "/bay"
url: "https://eliottvincent.github.io"
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: About
    - name: Research
    - name: Talks
    - name: CV

footer:
  show_powered_by: true
  contact:
    - type: email
      name: Email
      value: fshao@stu.pku.edu.cn
  
# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
